# Generated by Django 5.2.1 on 2025-06-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_birth_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('instructor', 'Инструктор'), ('admin', 'Администратор')], default='client', max_length=10, verbose_name='Роль'),
        ),
    ]
