# Generated by Django 5.2.1 on 2025-06-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Clients', 'Клиент'), ('Instructors', 'Инструктор'), ('Admins', 'Администратор')], default='client', verbose_name='Роль'),
        ),
    ]
