# Generated by Django 5.2.1 on 2025-06-03 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 3, 8, 55, 52, 446770, tzinfo=datetime.timezone.utc)),
        ),
    ]
