# Generated by Django 5.2.1 on 2025-06-03 16:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_schedulemodel_price_alter_commentsmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 3, 16, 53, 3, 891968, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='club.gymmodel', verbose_name='Зал'),
        ),
    ]
