# Generated by Django 5.2.1 on 2025-06-03 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_commentsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 3, 17, 7, 15, 108001, tzinfo=datetime.timezone.utc)),
        ),
    ]
