# Generated by Django 5.2.1 on 2025-06-03 22:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_commentsmodel_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название занятия')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Скидка')),
                ('end_time', models.DateTimeField(verbose_name='Окончание действия')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['end_time'],
            },
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 3, 22, 36, 34, 521592, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.promomodel'),
        ),
    ]
