# Generated by Django 5.2.1 on 2025-06-01 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='date',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='description',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='title',
        ),
        migrations.AddField(
            model_name='articles',
            name='api_id',
            field=models.IntegerField(default=1, unique=True, verbose_name='ID из API'),
        ),
        migrations.AddField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата сохранения'),
        ),
        migrations.AddField(
            model_name='articles',
            name='punchline',
            field=models.TextField(null=True, verbose_name='Ответ/Панчлайн'),
        ),
        migrations.AddField(
            model_name='articles',
            name='setup',
            field=models.TextField(null=True, verbose_name='Вопрос/Утверждение'),
        ),
        migrations.AddField(
            model_name='articles',
            name='type',
            field=models.CharField(choices=[('general', 'Общие'), ('programming', 'Программирование'), ('knock-knock', 'Тук-тук')], max_length=20, null=True, verbose_name='Тип шутки'),
        ),
    ]
