# Generated by Django 5.2.1 on 2025-06-02 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_remove_articles_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2025, 6, 2), null=True, verbose_name='Дата сохранения'),
        ),
    ]
