# Generated by Django 5.2.1 on 2025-06-02 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articles_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 18, 14, 20, 239437), null=True, verbose_name='Дата сохранения'),
        ),
    ]
