# Generated by Django 5.2.1 on 2025-06-02 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_articles_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 20, 41, 28, 664424, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата сохранения'),
        ),
    ]
