# Generated by Django 5.2.1 on 2025-06-03 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_alter_articles_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JokeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(default=1, unique=True, verbose_name='ID из API')),
                ('type', models.CharField(choices=[('general', 'Общие'), ('programming', 'Программирование'), ('knock-knock', 'Тук-тук')], max_length=20, null=True, verbose_name='Тип шутки')),
                ('setup', models.TextField(null=True, verbose_name='Вопрос/Утверждение')),
                ('punchline', models.TextField(null=True, verbose_name='Ответ/Панчлайн')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 3, 16, 53, 3, 891968, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата сохранения')),
            ],
            options={
                'verbose_name': 'Шутка',
                'verbose_name_plural': 'Шутка',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='articles',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='punchline',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='setup',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='type',
        ),
        migrations.AddField(
            model_name='articles',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 3, 16, 53, 3, 891968, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата сохранения'),
        ),
    ]
