# Generated by Django 5.2.1 on 2025-06-03 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_jokemodel_remove_articles_api_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img',
            field=models.FileField(blank=True, upload_to='news/img/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 3, 17, 7, 15, 108001, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата сохранения'),
        ),
        migrations.AlterField(
            model_name='jokemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 3, 17, 7, 15, 108001, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата сохранения'),
        ),
    ]
